#include <gtest/gtest.h>
#include "../../include/Services/PlayerManager.h"
#include "../../include/Services/PotManager.h"
#include "../../include/Services/ActionManager.h"
#include "../../include/Services/HandRankManager.h"
#include "../../include/Services/DealerManager.h"
#include "../../include/Utils/TestUtil.h"
#include "../../include/Utils/GameUtil.h"
#include "../../include/Utils/PrintUtil.h"

class PotTest : public::testing::Test {
protected:
    GameData gameData;
    PlayerManager playerManager;
    ActionManager actionManager;
    PotManager potManager;
    HandRankManager handRankManager;
    DealerManager dealer;

    vector<pair<string, size_t>> playersInfo = 
    {
        {"P1", 100},
        {"P2", 200},
        {"P3", 300},
        {"P4", 400},
        {"P5", 500},
        {"P6", 400},
        {"P7", 300},
        {"P8", 200},
        {"P9", 100}
    };

    PotTest() : 
        playerManager(gameData), 
        actionManager(gameData),
        potManager(gameData),
        handRankManager(gameData),
        dealer(gameData)
    {
            playerManager.addNewPlayers(TestUtil::getSubset(playersInfo, 0, 9));
    }

    void TearDown() override {
        TestUtil::manualClearActionTimeline(gameData);
        TestUtil::manualClearPots(gameData);
    }

    // For each action, adds the action to timeline
    void parseActionTimeline(vector<tuple<string, ActionType, size_t>> actionTimeline) {
        for (auto& [id, action, amount] : actionTimeline) {
            actionManager.addNewAction(id, action, amount);
        }
    }

    // Verifies if the Pot Manager evaluates pots and dead chips as expected
    void verifyPotCalculation(vector<pair<size_t, vector<string>>> expectedPots, size_t expectedDeadChips) {
        potManager.calculatePots();
        EXPECT_EQ(TestUtil::getPotsChipsAndNames(gameData), expectedPots);
        EXPECT_EQ(gameData.getDeadChips(), expectedDeadChips);
    }

    // Verifies if the Pot Manager correctly awards pots to players according
    // to the player ranking generated by the Hand Evaluator
    void verifyPotAwardedCorrectly(vector<pair<string, size_t>> expectedChipsToNames) {
        potManager.awardPots();
        auto actualChipsToNames = GameUtil::getPlayersCurChips(gameData);
        EXPECT_EQ(actualChipsToNames, expectedChipsToNames);
    }
};

TEST_F(PotTest, NoSidePot) {
    vector<tuple<string, ActionType, size_t>> betCalled = {
        {"P1", ActionType::BET, 5},
        {"P2", ActionType::CALL, 5},
        {"P3", ActionType::CALL, 5},
        {"P4", ActionType::CALL, 5},
        {"P5", ActionType::CALL, 5},
        {"P6", ActionType::CALL, 5},
        {"P7", ActionType::CALL, 5},
        {"P8", ActionType::CALL, 5},
        {"P9", ActionType::CALL, 5},
    };
    parseActionTimeline(betCalled);
    verifyPotCalculation(
    {
        {45, {"P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9"}}
    }, 0);
};

TEST_F(PotTest, SingleSidePot) {
    vector<tuple<string, ActionType, size_t>> singleSidePot = {
        {"P1", ActionType::ALL_IN_BET, 100},
        {"P2", ActionType::ALL_IN_RAISE, 200},
        {"P3", ActionType::CALL, 200},
        {"P4", ActionType::CALL, 200},
        {"P5", ActionType::CALL, 200},
        {"P6", ActionType::CALL, 200},
        {"P7", ActionType::CALL, 200},
        {"P8", ActionType::ALL_IN_CALL, 200},
        {"P9", ActionType::ALL_IN_CALL, 100},
    };
    parseActionTimeline(singleSidePot);
    verifyPotCalculation(
    {
        {900, {"P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9"}},
        {700, {"P2", "P3", "P4", "P5", "P6", "P7", "P8"}}
    }, 0);
};

TEST_F(PotTest, MultipleSidePots) {
    vector<tuple<string, ActionType, size_t>> multipleSidePots = {
        {"P1", ActionType::ALL_IN_BET, 100},
        {"P2", ActionType::ALL_IN_RAISE, 200},
        {"P3", ActionType::ALL_IN_RAISE, 300},
        {"P4", ActionType::ALL_IN_RAISE, 400},
        {"P5", ActionType::CALL, 400},
        {"P6", ActionType::ALL_IN_CALL, 400},
        {"P7", ActionType::ALL_IN_CALL, 300},
        {"P8", ActionType::ALL_IN_CALL, 200},
        {"P9", ActionType::ALL_IN_CALL, 100},
    };
    parseActionTimeline(multipleSidePots);
    verifyPotCalculation(
    {
        {900, {"P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9"}},
        {700, {"P2", "P3", "P4", "P5", "P6", "P7", "P8"}},
        {500, {"P3", "P4", "P5", "P6", "P7"}},
        {300, {"P4", "P5", "P6"}}
    }, 0);
};

TEST_F(PotTest, DeadMoney) {
    vector<tuple<string, ActionType, size_t>> playersFoldAfterBet = {
        {"P1", ActionType::ALL_IN_BET, 100},
        {"P2", ActionType::ALL_IN_RAISE, 200},
        {"P3", ActionType::ALL_IN_RAISE, 300},
        {"P4", ActionType::ALL_IN_RAISE, 400},
        {"P5", ActionType::CALL, 400},
        {"P6", ActionType::FOLD, 0},
        {"P7", ActionType::FOLD, 0},
        {"P8", ActionType::FOLD, 0},
        {"P9", ActionType::FOLD, 0},
        {"P1", ActionType::FOLD, 0},
        {"P2", ActionType::FOLD, 0},
        {"P3", ActionType::FOLD, 0},
    };
    parseActionTimeline(playersFoldAfterBet);
    verifyPotCalculation(
    {
        {1400, {"P4", "P5"}},
    }, 0);
};

TEST_F(PotTest, AwardToPlayers) {
    // Suppose all 9 players go all-in
    vector<tuple<string, ActionType, size_t>> allPlayersShove = {
        {"P1", ActionType::ALL_IN_BET, 100},
        {"P2", ActionType::ALL_IN_RAISE, 200},
        {"P3", ActionType::ALL_IN_RAISE, 300},
        {"P4", ActionType::ALL_IN_RAISE, 400},
        {"P5", ActionType::CALL, 400},
        {"P6", ActionType::ALL_IN_CALL, 400},
        {"P7", ActionType::ALL_IN_CALL, 300},
        {"P8", ActionType::ALL_IN_CALL, 200},
        {"P9", ActionType::ALL_IN_CALL, 100},
    };
    parseActionTimeline(allPlayersShove);
    verifyPotCalculation(
    {
        {900, {"P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9"}},
        {700, {"P2", "P3", "P4", "P5", "P6", "P7", "P8"}},
        {500, {"P3", "P4", "P5", "P6", "P7"}},
        {300, {"P4", "P5", "P6"}}
    }, 0);

    // Evaluate player hands and evaluate the ranking of player IDs

    vector<pair<Suit, Value>> cards = {
        // Boards
        {Suit::CLUBS, Value::FOUR},
        {Suit::CLUBS, Value::FIVE},
        {Suit::CLUBS, Value::SIX},
        {Suit::SPADES, Value::SEVEN},
        {Suit::SPADES, Value::ACE},

        // Player 1: 6 Straight Flush 
        {Suit::CLUBS, Value::TWO},
        {Suit::CLUBS, Value::THREE},

        // Player 2: K Flush
        {Suit::CLUBS, Value::KING},
        {Suit::CLUBS, Value::QUEEN},

        // Player 3: 4-5 2-Pair
        {Suit::HEARTS, Value::FOUR},
        {Suit::HEARTS, Value::FIVE},

        // Player 4: 9 Straight
        {Suit::HEARTS, Value::EIGHT},
        {Suit::HEARTS, Value::NINE},

        // Player 5: A Pair 2 Kicker
        {Suit::HEARTS, Value::ACE},
        {Suit::HEARTS, Value::TWO},

        // Player 6: A Pair 10 Kicker
        {Suit::DIAMONDS, Value::ACE},
        {Suit::HEARTS, Value::TEN},

        // Player 7: A-7 2-Pair
        {Suit::CLUBS, Value::ACE},
        {Suit::HEARTS, Value::SEVEN},

        // Player 8: J Flush
        {Suit::CLUBS, Value::JACK},
        {Suit::CLUBS, Value::TEN},

        // Player 9: 4 Three of a Kind
        {Suit::DIAMONDS, Value::FOUR},
        {Suit::SPADES, Value::FOUR}
    };

    auto actual = TestUtil::evaluateHandsAndGetRankedNames(gameData, handRankManager, cards);
    EXPECT_EQ(actual, vector<string>({"P1", "P2", "P8", "P4", "P9", "P7", "P3", "P6", "P5"}));

    // P1 wins Pot 1 (900), P2 wins Pot 2 (700), P4 wins Pot 3 (500) and 4 (300)
    // P5 has 100 remaining, everyone else busts
    vector<pair<string, size_t>> expectedChips = {
        {"P1", 900},
        {"P2", 700},
        {"P3", 0},
        {"P4", 300 + 500},
        {"P5", 100}, 
        {"P6", 0},
        {"P7", 0},
        {"P8", 0},
        {"P9", 0}
    };

    verifyPotAwardedCorrectly(expectedChips);
}